layout_spectrum: 0.9342329
color:
  saturation: 0.4563502
  lightness: 0.4641577
  brandStrength: 0.9902752
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#C6C6C6'
    - '#272727'
    - '#919191'
  rhythmicContrast: 0.2051634
typography_spectrum: 0.1057348
name: intomotive
